configurations:
# Generates the ConfigOptions Markdown documentation
- output: Docs/ConfigOptions.md
  parseDocumentation: true
  templates:
  - Sourcery/ConfigOptions.md.stencil
  sources:
  - Sources/CreateOptions/ConfigOptions.swift
