// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct SortSwiftyProperties: Codable {
	public var id: String
	public var isLikesMeat: Bool?
	public var isAllergic: Bool?

	public init(id: String, isLikesMeat: Bool? = nil, isAllergic: Bool? = nil) {
		self.id = id
		self.isLikesMeat = isLikesMeat
		self.isAllergic = isAllergic
	}

	public init(from decoder: Decoder) throws {
		let values = try decoder.container(keyedBy: StringCodingKey.self)
		self.id = try values.decode(String.self, forKey: "id")
		self.isLikesMeat = try values.decodeIfPresent(Bool.self, forKey: "likesMeat")
		self.isAllergic = try values.decodeIfPresent(Bool.self, forKey: "allergic")
	}

	public func encode(to encoder: Encoder) throws {
		var values = encoder.container(keyedBy: StringCodingKey.self)
		try values.encode(id, forKey: "id")
		try values.encodeIfPresent(isLikesMeat, forKey: "likesMeat")
		try values.encodeIfPresent(isAllergic, forKey: "allergic")
	}
}
