// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct SortSwiftyProperties: Codable {
    public var id: String
    public var isAllergic: Bool?
    public var isLikesMeat: Bool?

    public init(id: String, isAllergic: Bool? = nil, isLikesMeat: Bool? = nil) {
        self.id = id
        self.isAllergic = isAllergic
        self.isLikesMeat = isLikesMeat
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decode(String.self, forKey: "id")
        self.isAllergic = try values.decodeIfPresent(Bool.self, forKey: "allergic")
        self.isLikesMeat = try values.decodeIfPresent(Bool.self, forKey: "likesMeat")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(id, forKey: "id")
        try values.encodeIfPresent(isAllergic, forKey: "allergic")
        try values.encodeIfPresent(isLikesMeat, forKey: "likesMeat")
    }
}
