// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation

/// A pet title
///
/// A pet description
public struct Pet: Codable {
    /// Example: "Buddy"
    public var name: String
    public var tag: String?

    public init(name: String, tag: String? = nil) {
        self.name = name
        self.tag = tag
    }
}
