// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import HTTPHeaders
import URLQueryEncoder

extension Paths {
    static var pets: Pets {
        Pets(path: "/pets")
    }

    struct Pets {
        /// Path: `/pets`
        let path: String

        /// List all pets
        func get(limit: Int? = nil) -> Request<[internal_access_control.Pet]> {
            Request(method: "GET", url: path, query: makeGetQuery(limit), id: "listPets")
        }

        enum GetResponseHeaders {
            /// A link to the next page of responses
            static let next = HTTPHeader<String>(field: "x-next")
        }

        private func makeGetQuery(_ limit: Int?) -> [(String, String?)] {
            let encoder = URLQueryEncoder()
            encoder.encode(limit, forKey: "limit")
            return encoder.items
        }

        /// Create a pet
        var post: Request<Void> {
            Request(method: "POST", url: path, id: "createPets")
        }
    }
}
