// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct SortSwiftyProperties: Codable {
    public var id: String
    public var isLikesMeat: Bool?
    public var isAllergic: Bool?

    public init(id: String, isLikesMeat: Bool? = nil, isAllergic: Bool? = nil) {
        self.id = id
        self.isLikesMeat = isLikesMeat
        self.isAllergic = isAllergic
    }

    private enum CodingKeys: String, CodingKey {
        case id
        case isLikesMeat = "likesMeat"
        case isAllergic = "allergic"
    }
}
