// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

struct Error: Codable {
    var code: Int
    var message: String

    init(code: Int, message: String) {
        self.code = code
        self.message = message
    }
}
